name: build ci.cd

on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main" ]

env:
  GH_TOKEN: ${{ secrets.WORKFLOW_GH_TOKEN }}
  
permissions:
  contents: write

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        ghToken:         ${{ secrets.WORKFLOW_GH_TOKEN }}
        GH_TOKEN:        ${{ secrets.WORKFLOW_GH_TOKEN }}
        repositoryPath:  ${{ github.workspace }}
        repository:      ${{ github.repository }}
        repositoryOwner: ${{ github.repository_owner }}
        ref:             ${{ github.event.client_payload.ref || github.ref }}
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
        submodules: 'recursive'
    - name: npm ci
      run: npm ci
    - name: Run buildMiruken.js
      run:  node ./deployment/buildMiruken.js 
