name: build ci.cd

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        ghToken:         ${{ secrets.CI_CD_TOKEN }}
        GH_TOKEN:        ${{ secrets.CI_CD_TOKEN }}
        repositoryPath:  ${{ github.workspace }}
        repository:      ${{ github.repository }}
        repositoryOwner: ${{ github.repository_owner }}
        ref:             ${{ github.event.client_payload.ref || github.ref }}
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
        submodules: 'recursive'
    - run:  npm ci
    - run:  npm run test
    - run:  npm run publish
